### ISSUE TITLE
Issues receiving short messages

### ISSUE THREAD

**Issue by jeefo88** [greenaddress/GreenAddressWebFiles#24] opened 2016-10-03 21:26 UTC
Hey guys, nomerous reports of not receiving confirmation sms codes in Ukraine and Russia. Please take care ASAP.

**Comment by greenaddress** [comment] 2016-10-03 21:34
@jeefo88 thanks, we are looking into it - it seems this problem is affecting a number of companies (including github 2FA at least for Ukraine) - we'll close this issue once we know is resolved

**Comment by greenaddress** [comment] 2016-10-03 21:39
For other people reading this issue: even once this issue is resolved we are finding SMS quite unreliable compared to the other 2FA options and in general it is important to have a 2FA backup option enabled as we are not simply able to disable 2FA for affected users.

**Comment by jeefo88** [comment] 2016-10-03 22:55
@greenaddress any updates for this moment? Emergency upcoming.

**Comment by greenaddress** [comment] 2016-10-03 23:16
@jeefo88 the only update is that we created a new ticket with our upstream SMS provider. Once we have any update we'll provide an update here.

**Comment by greenaddress** [comment] 2016-10-03 23:17
For what is worth not all SMS are failing, just some, perhaps related to some specific mobile operators, not sure yet.

**Comment by jeefo88** [comment] 2016-10-04 08:47
I can confirm that - sms was delivered to one of the operators. However, I'm now getting 'request rate limit exceeded'. How soon will this limit be reset?

**Comment by jeefo88** [comment] 2016-10-04 10:29
@greenaddress nevermind limit question. it's been reset

**Comment by jeefo88** [comment] 2016-10-04 10:48
@greenaddress problem affects Ukrainian operators 
Kyivstar: +38067, +38096, +38097, +38098, +38068
Lifecell: +38063, +38093, +38073

Does NOT affect Vodafone UA: +38066, +38095, +38050

**Comment by greenaddress** [comment] 2016-10-05 17:25
Small update: Apparently the issue is not at our SMS provider but their own provider and they have pushed the request to fix this issue upstream to their own provider.

We'll continue to monitor the situation and alternatives to fix the issue and we will provide an update as soon as there's any.

**Comment by greenaddress** [comment] 2016-10-07 09:19
@jeefo88 our provider confirmed there have been a few route changes.

Can you let us know if there are still problems? If so, it would be helpful to have the exact time you tried so we can look it up (but please avoid providing private information like mobile numbers here)

thanks!

**Comment by jeefo88** [comment] 2016-10-07 10:00
@greenaddress works fine now. Thanks!

**Comment by greenaddress** [comment] 2016-10-07 10:09
great! thanks!

Closing.

**Closed by greenaddress** 2016-10-07 10:09 UTC

**Comment by zerlani** [comment] 2016-12-30 11:47
Please help me ,  I do not have an email set and do not have a phone registered for operate on the wallet. Can You help me????
I have only access to my wallet but I cant use it. Help me
Can You change my email to receive the code to operate on the wallet?
I will give you all the infos You need , but help me please
It seems no email is set and no phone set to receive sms
I’m really desperate
Greetings

**Comment by zerlani** [comment] 2016-12-30 15:25
or simply add an option to let us disable the 2fa temporarly

**Comment by pptp** [comment] 2017-06-03 20:17
Hi guys!
The problem with receiving sms repeats in Russia.
I cannot get confirmation sms for several days and have not another 2fa option configured (yes, it is a bad practice).
